Hw04 lru cache
LSandrov/otus-hw pull request #5
Opened 2022-04-17 07:36 UTC by LSandrov

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-04-20 15:20 UTC, agneum approved these changes
Спасибо за выполненное задание. 
Хорошая работа, однако возвращаю на доработку, поскольку пайплайн не пройдён и есть предложения по улучшению
Итого: 5 баллов из 10

2022-04-20 15:20 UTC, agneum commented on hw04_lru_cache/go.mod
> +module github.com/LSandrov/hw04_lru_cache
Важно указать полный путь до пакета, иначе тесты и линтеры не пройдут.
Сейчас пайплайн красный

2022-04-20 15:20 UTC, agneum commented on hw04_lru_cache/cache.go
> +	pushed := c.queue.PushFront(item)
Желательно сначала проверить `capacity`, а затем добавлять элемент, иначе возникнет момент времени, когда количество элементов на один превысит `capacity`

2022-04-20 15:20 UTC, agneum commented on hw04_lru_cache/cache.go
> +			return false
Рекомендую при взятии лока сразу использовать `defer c.mu.Unlock()`, чтобы гарантированно отпустить его при всех выходах из функции

2022-04-20 15:20 UTC, agneum commented on hw04_lru_cache/cache.go
> +			return nil, false
Аналогично, лок не освобождён

2022-04-20 15:20 UTC, agneum commented on hw04_lru_cache/cache.go
> +		delete(c.items, i)
Можно переинициализировать поле без полного перебора

2022-04-20 15:20 UTC, agneum commented on hw04_lru_cache/list.go
> +		l.front = listItem
`l.front` устанавливается позже, строку можно убрать как дублирующую

2022-04-20 15:20 UTC, agneum commented on hw04_lru_cache/list.go
> +		l.back = listItem
Нужен `l.front`

2022-04-20 15:20 UTC, agneum commented on hw04_lru_cache/list.go
> +func pos(l *list, i *ListItem) {
Почему бы не сделать эту функцию методом списка (`l *list`)?

2022-04-20 15:22 UTC, agneum requested changes
Спасибо за выполненное задание.
Хорошая работа, однако возвращаю на доработку, поскольку пайплайн не пройдён и есть предложения по улучшению
Итого: 5 баллов из 10

2022-04-22 09:56 UTC, LSandrov commented on hw04_lru_cache/go.mod
> +module github.com/LSandrov/hw04_lru_cache
Странно почему у вас отобразились красные джобы, у меня показывает, что все ок https://github.com/LSandrov/otus-hw/actions/runs/2179273668

2022-04-23 13:28 UTC, agneum commented on hw04_lru_cache/go.mod
> +module github.com/LSandrov/hw04_lru_cache
Вкладка checks в этом PR: https://github.com/LSandrov/otus-hw/pull/5/checks

2022-04-27 14:20 UTC, LSandrov commented on hw04_lru_cache/go.mod
> +module github.com/LSandrov/hw04_lru_cache
Это был первый прогон. Если посмотреть, там есть следующие и с ними все ок

2022-04-27 15:27 UTC, agneum approved these changes
Спасибо за правки. Хорошая работа.
Итого: 9 баллов из 10

2022-04-27 15:27 UTC, agneum commented on hw04_lru_cache/list.go
> +		l.back = listItem
Опечатка же: `l.front` так и останется не заданным

2022-04-27 17:22 UTC, merged